### ISSUE TITLE
Rspec-core Role constant missing in rails 3 app

### ISSUE THREAD

**Issue by feliksg** [kristianmandrup/cream#1] opened 2010-09-29 21:45 UTC
Hi, i'm trying out cream for a rails 3 app i'm building...it's a freshly generated rails 3 app with cream and devise gems included in the gemfile.

When I try to run rails g devise:install or rails g permits, I get the following error message: 
gems/ruby-1.9.2-p0/gems/rspec-core-2.0.0.beta.22/lib/rspec/core/backward_compatibility.rb:20:in `const_missing': uninitialized constant Role (NameError)

Am I missing something in my gemfile?  I saw that bundler installed a bunch of other gems with cream...

Any help will be appreciated.  Thank you.

**Comment by kristianmandrup** [comment] 2010-09-30 07:51
I think you should first take a look at my Demo app, cream-rails-app at http://github.com/kristianmandrup/cream-rails3-app 
Also, the error you sent me is not sufficient for me to really see what went wrong. Please submit a more comprehensive stacktrace, at least containing the line of something related to cream that caused the error, and not from some other lib like rspec-core which is pretty much meaningless in order to debug the cause.

Hopefully I will have time this weekend to make it easier to set it all up and have more comprehensive examples etc. Which role strategy did you use? I can imagine that you haven't created a Role model.

**Comment by kristianmandrup** [comment] 2010-12-10 20:33
This has been fixed now. Use Cream 0.8 and above ;)

**Closed as completed by kristianmandrup** 2010-12-10 20:33 UTC
